version: '3.7'
services:
  front-spotify:
    container_name: spotify-container
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'